import type { Material } from "@/types/material";

export const MOCK_MATERIALS: Material[] = [
  {
    id: 1,
    title: "Apuntes Cálculo Diferencial — Semestre 2024-1",
    cat: "pub", type: "PDF",
    subject: "Cálculo", uni: "Universidad Nacional",
    author: "Laura M.", date: "12 mar 2025", size: "3.2 MB",
    desc: "Notas completas de clase con ejemplos resueltos, parciales anteriores y fórmulas clave. Cubre derivadas, límites y aplicaciones.",
    downloads: 87,
  },
  {
    id: 2,
    title: "Guía rápida de Termodinámica",
    cat: "pub", type: "PDF",
    subject: "Termodinámica", uni: "EAFIT",
    author: "Carlos R.", date: "5 abr 2025", size: "1.8 MB",
    desc: "Resumen visual con diagramas de los principios de Termodinámica para preparación de parciales.",
    downloads: 54,
  },
  {
    id: 3,
    title: "Parcial resuelto — Estructuras de Datos",
    cat: "bus", type: "DOC",
    subject: "Prog. Avanzada", uni: "Uniandes",
    author: "Diego T.", date: "20 feb 2025", size: "0.9 MB",
    desc: "Solución comentada del segundo parcial de Estructuras de Datos con análisis de complejidad.",
    downloads: 120,
  },
  {
    id: 4,
    title: "Fotografías históricas — Arquitectura Republicana",
    cat: "rec", type: "IMG",
    subject: "Historia del Arte", uni: "Universidad de los Andes",
    author: "Sofía P.", date: "1 mar 2025", size: "45 MB",
    desc: "Colección de 80 fotografías de alta resolución de edificaciones republicanas en Bogotá para investigación académica.",
    downloads: 33,
  },
  {
    id: 5,
    title: "Taller de estadística descriptiva completo",
    cat: "pub", type: "DOC",
    subject: "Estadística", uni: "UPB",
    author: "Manuela G.", date: "10 abr 2025", size: "2.1 MB",
    desc: "Taller con 30 ejercicios de estadística descriptiva: tablas de frecuencias, medidas de tendencia central y gráficos.",
    downloads: 68,
  },
  {
    id: 6,
    title: "Mecánica de Fluidos — Flujo laminar y turbulento",
    cat: "bus", type: "VID",
    subject: "Mecánica de Fluidos", uni: "Universidad Nacional",
    author: "Andrés B.", date: "28 mar 2025", size: "180 MB",
    desc: "Video explicativo de 45 minutos sobre flujo laminar y turbulento con simulaciones visuales y problemas resueltos.",
    downloads: 29,
  },
];
